[package]
name = "leetcode"
version = "0.1.0"
authors = ["Provotorov <provotorov@inbox.ru>"]
edition = "2021"
repository = "https://github.com/LigeronAhill/leetcode_on_Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
